### ISSUE TITLE
Escape characters are not converted

### ISSUE THREAD

**Issue by diegobas** [danharrin/date-format-converter#1]
**Describe the bug**
When trying to convert a PHP format string with escape characters, those are not converted

**To reproduce**
$format = 'l, j \d\e F \d\e Y';

\d & \e are converted as 'd' and 'e' ignoring '\\'

**Expected behavior**
'\d\e' must be converted as '[de]'

**Context**
- Package version: latest
- Server OS: WAMPServer on Windows
- PHP version: 8.0.3

**Additional details**
Next code works for me, but might exist better solutions for sure.

```
public function to($standard)
    {
        $format = '';

        $escape = false;
        foreach (str_split($this->format) as $token) {
            if ($escape) {
                $format .= "[{$token}]";
                $escape = false;
                continue;
            }

            if ($token === '\\') {
                $escape = true;
                continue;
            }

            $format .= array_key_exists($token, DATE_FORMAT_STANDARDS) ?
                DATE_FORMAT_STANDARDS[$token][$standard] :
                $token;
        }

        $format = str_replace('][', '', $format);

        return $format;
    }
```

**Comment by danharrin** [comment]
Fixed by #2.
